export interface Env {
  MONGO_LOGIN: 'MONGO_LOGIN';
  MONGO_PASSWORD: 'MONGO_PASSWORD';
  MONGO_AUTHDATABASE: 'MONGO_AUTHDATABASE';
  MONGO_HOST: 'MONGO_HOST';
  MONGO_PORT: 'MONGO_PORT';
  JWT_SECRET: 'JWT_SECRET';
  DOMAIN: 'DOMAIN';
  HH_TOKEN: 'HH_TOKEN';
}
